# Generated by Django 4.0.5 on 2022-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_sellerregistration_managementregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('eid', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('team_no', models.CharField(max_length=200)),
            ],
        ),
    ]
