# Generated by Django 4.0.5 on 2022-09-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_team_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team_details',
        ),
    ]
