# Generated by Django 4.0.5 on 2022-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('employment', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('zip', models.PositiveBigIntegerField(null=True)),
                ('place', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('code', models.PositiveBigIntegerField(null=True)),
                ('phone', models.PositiveBigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('approve', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('km_driven', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('No_of_Owners', models.CharField(max_length=200)),
                ('Registration_City', models.CharField(max_length=200)),
                ('car_type', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=200)),
                ('rc', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
