# Generated by Django 4.0.5 on 2022-09-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('km_driven', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('No_of_Owners', models.CharField(max_length=200)),
                ('Registration_City', models.CharField(max_length=200)),
                ('car_type', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=200)),
                ('rc', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
