# Generated by Django 4.0.5 on 2022-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
