# Generated by Django 4.0.5 on 2022-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_details_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
