# Generated by Django 4.0.5 on 2022-09-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_vehicle_details_approve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seller_details',
            new_name='seller_details_1',
        ),
    ]
