# Generated by Django 4.0.5 on 2022-09-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_details_vehicle_details'),
        ('seller', '0008_seller_details_delete_seller_details_1'),
    ]

    operations = [
    ]
