# Generated by Django 4.0.5 on 2022-09-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyer_details',
            new_name='buyer_details_1',
        ),
    ]
