# Generated by Django 4.0.5 on 2022-09-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_buyer_details_buyer_details_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer_details_1',
            old_name='comment',
            new_name='No_of_Owners',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='code',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='company',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='country',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='place',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='street',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='title',
        ),
        migrations.RemoveField(
            model_name='buyer_details_1',
            name='zip',
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='car_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='fuel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details_1',
            name='transmission',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_details_1',
            name='employment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_details_1',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_details_1',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
