# Generated by Django 4.0.5 on 2022-09-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_rename_comment_buyer_details_1_no_of_owners_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employment', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('car_type', models.CharField(max_length=200, null=True)),
                ('fuel', models.CharField(max_length=200, null=True)),
                ('transmission', models.CharField(max_length=200, null=True)),
                ('No_of_Owners', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='buyer_details_1',
        ),
    ]
