# Generated by Django 4.0.5 on 2022-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_team_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanical_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('km', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('engine', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('gear', models.CharField(max_length=200)),
                ('gear_condition', models.CharField(max_length=200)),
                ('air_bag', models.CharField(max_length=200)),
                ('airbag_condition', models.CharField(max_length=200)),
                ('tyre_condition', models.CharField(max_length=200)),
                ('light_condition', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
