# Generated by Django 4.0.5 on 2022-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_mechanical_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='quotation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
