# Generated by Django 4.0.5 on 2022-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_mechanical_analysis_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanical_analysis',
            name='quotation',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
