# Generated by Django 4.0.5 on 2022-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_mechanical_analysis_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='to_seller',
            field=models.BooleanField(default=False),
        ),
    ]
