# Generated by Django 4.0.5 on 2022-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_mechanical_analysis_to_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanical_analysis',
            name='deny',
            field=models.BooleanField(default=False),
        ),
    ]
