# Generated by Django 4.0.5 on 2022-10-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_mechanical_analysis_accept_mechanical_analysis_deny'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='smart_contract',
            field=models.BooleanField(default=False),
        ),
    ]
