# Generated by Django 4.0.5 on 2022-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_mechanical_analysis_smart_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='bid',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
