# Generated by Django 4.0.7 on 2023-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_mechanical_analysis_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='car_encrypt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechanical_analysis',
            name='condition_encrypt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechanical_analysis',
            name='gear_condition_encrypt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechanical_analysis',
            name='km_encrypt',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mechanical_analysis',
            name='year_encrypt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
