# Generated by Django 4.0.7 on 2023-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_mechanical_analysis_car_encrypt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanical_analysis',
            name='hash_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
