# Generated by Django 4.0.7 on 2023-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_mechanical_analysis_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanical_analysis',
            name='quotation',
            field=models.IntegerField(null=True),
        ),
    ]
