# Generated by Django 4.0.7 on 2023-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_mechanical_analysis_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_details',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
